// 精神分析概念网络数据结构
export interface ConceptNode {
  id: string;
  name: string;
  nameEn: string;
  description: string;
  definition?: string; // 详细定义
  example?: string; // 案例说明
  category: 'core' | 'personality' | 'defense' | 'therapy' | 'phenomena' | 'theorist' | 'lacan' | 'self_psychology' | 'object_relations';
  level: number; // 0: 中心, 1: 第一层, 2: 第二层, 3: 第三层
  color: string;
  icon?: string;
  avatar?: string; // 头像URL
}

export interface ConceptLink {
  source: string;
  target: string;
  type: 'relates' | 'influences' | 'contains' | 'treats' | 'manifests';
  strength: number; // 0-1
}

export const conceptNodes: ConceptNode[] = [
  // 核心概念 - 中心
  {
    id: 'unconscious',
    name: '无意识',
    nameEn: 'Unconscious',
    description: '精神分析的基础。包含被压抑的思想、欲望和记忆，对行为有强大影响。',
    definition: '无意识是指个体不能直接认识到的心理过程和内容，包括被压抑的欲望、冲突和创伤记忆。它对个体的行为、情感和思维方式产生深远影响，但个体通常无法意识到这些影响的来源。',
    example: '一个人可能无法解释自己对某种特定情况的强烈恐惧反应，这种恐惧可能源于童年的创伤记忆，已被压入无意识中。',
    category: 'core',
    level: 0,
    color: '#D97706',
  },

  // 第一层：人格结构
  {
    id: 'id',
    name: '本我',
    nameEn: 'Id',
    description: '最原始、最基本的人格部分。遵循享乐原则，追求即时满足。',
    definition: '本我是人格中最原始的部分，完全无意识，遵循享乐原则。它追求即时的满足，不考虑现实或道德约束，是所有本能冲动和欲望的源头。',
    example: '婴儿饿了就哭闹要求喂食，这就是本我的直接表现——无条件地追求满足生理需求。',
    category: 'personality',
    level: 1,
    color: '#F59E0B',
  },
  {
    id: 'ego',
    name: '自我',
    nameEn: 'Ego',
    description: '人格的理性部分。处理现实世界，平衡本我和超我的冲突。',
    definition: '自我是人格中的理性部分，部分意识，部分无意识。它遵循现实原则，与现实世界互动，并调解本我的冲动与超我的道德要求之间的冲突。',
    example: '一个人感到饥饿（本我），但意识到现在不是吃饭的时间，所以等待午餐时间再吃（自我的理性决定）。',
    category: 'personality',
    level: 1,
    color: '#A78BFA',
  },
  {
    id: 'superego',
    name: '超我',
    nameEn: 'Superego',
    description: '道德和良知的代表。内化社会规范和父母的期望。',
    definition: '超我代表道德和理想，是个体内化的社会规范、父母的价值观和道德标准。它通过内疚感和羞愧感来约束本我的冲动，追求完美和道德的行为。',
    example: '一个人想要说谎来逃避责任，但超我产生的内疚感使其最终选择诚实面对。',
    category: 'personality',
    level: 1,
    color: '#60A5FA',
  },

  // 第二层：防御机制
  {
    id: 'repression',
    name: '压抑',
    nameEn: 'Repression',
    description: '将不可接受的想法、欲望或记忆推入无意识。',
    definition: '压抑是最基本的防御机制，指将令人不快、冲突或威胁的思想、欲望或记忆推入无意识，使个体无法直接意识到它们。',
    example: '一个遭受童年虐待的人可能完全无法记起这些创伤事件，因为这些记忆被压入了无意识。',
    category: 'defense',
    level: 2,
    color: '#A78BFA',
  },
  {
    id: 'denial',
    name: '否认',
    nameEn: 'Denial',
    description: '拒绝承认令人不安的现实或真相。',
    definition: '否认是一种防御机制，个体拒绝承认或接受令人不安的现实、事实或真相，仿佛这些事情不存在。',
    example: '一个被诊断出患有严重疾病的患者坚持认为医生的诊断是错误的，尽管有明确的医学证据。',
    category: 'defense',
    level: 2,
    color: '#A78BFA',
  },
  {
    id: 'projection',
    name: '投射',
    nameEn: 'Projection',
    description: '将自己的不可接受特质归咎于他人。',
    definition: '投射是指个体将自己不能接受的想法、欲望或特质无意识地归咎于他人，从而避免承认这些特质属于自己。',
    example: '一个潜意识中有不忠想法的人可能会不断怀疑伴侣的忠诚度。',
    category: 'defense',
    level: 2,
    color: '#A78BFA',
  },
  {
    id: 'sublimation',
    name: '升华',
    nameEn: 'Sublimation',
    description: '将本能冲动转化为社会可接受的活动。',
    definition: '升华是一种积极的防御机制，将不可接受的本能冲动（如攻击欲望或性欲）转化为社会可接受的活动，如艺术、运动或学术研究。',
    example: '一个人将内心的愤怒和挫折感转化为创作激情，创作出充满力量的艺术作品。',
    category: 'defense',
    level: 2,
    color: '#A78BFA',
  },

  // 第二层：治疗方法
  {
    id: 'free_association',
    name: '自由联想',
    nameEn: 'Free Association',
    description: '分析者说出想到的任何事情，揭示无意识内容。',
    definition: '自由联想是精神分析的基本技术，要求分析者在放松的状态下，自由地说出脑海中浮现的任何想法、感受或意象，不加审查或逻辑组织。',
    example: '分析师要求患者躺在沙发上，自由地说出任何想到的事情，从而帮助揭示无意识的冲突和欲望。',
    category: 'therapy',
    level: 2,
    color: '#34D399',
  },
  {
    id: 'dream_analysis',
    name: '梦的解析',
    nameEn: 'Dream Analysis',
    description: '通过解释梦来了解无意识的欲望和冲突。',
    definition: '梦的解析是精神分析的重要方法，通过分析梦的内容、象征和隐喻来理解无意识的欲望、冲突和心理问题。梦被视为通往无意识的"皇家之路"。',
    example: '患者梦到被追赶，分析师帮助患者理解这个梦可能代表对某种现实冲突的逃避或对权威的恐惧。',
    category: 'therapy',
    level: 2,
    color: '#34D399',
  },
  {
    id: 'transference',
    name: '转移',
    nameEn: 'Transference',
    description: '分析者将对他人的感情投射到分析师身上。',
    definition: '转移是指分析者将对过去重要人物（如父母）的感情、态度和期望无意识地投射到分析师身上。这是治疗中的关键现象，可以揭示个体的深层心理冲突。',
    example: '一个患者可能将对父亲的恐惧投射到男性分析师身上，表现出过度的尊敬或恐惧。',
    category: 'therapy',
    level: 2,
    color: '#34D399',
  },
  {
    id: 'interpretation',
    name: '解释',
    nameEn: 'Interpretation',
    description: '分析师帮助分析者理解无意识的意义。',
    definition: '解释是分析师的主要工作，通过指出分析者言语、行为或梦中的隐藏意义，帮助其获得对无意识过程的洞察和理解。',
    example: '分析师指出患者反复提及的某个细节可能与其童年创伤有关，帮助患者建立起这种联系。',
    category: 'therapy',
    level: 2,
    color: '#34D399',
  },

  // 第二层：心理现象
  {
    id: 'psychic_determinism',
    name: '精神决定论',
    nameEn: 'Psychic Determinism',
    description: '所有心理过程都不是自发的，而是受无意识决定。',
    definition: '精神决定论认为所有心理过程、行为和思想都不是随意的，而是由无意识的动机、欲望和过去经历决定的。没有真正的偶然，每个行为都有其无意识的原因。',
    example: '一个人"不小心"忘记了重要的约会，实际上可能是无意识地想要避免这个约会。',
    category: 'phenomena',
    level: 2,
    color: '#F472B6',
  },
  {
    id: 'oedipus_complex',
    name: '俄狄浦斯情结',
    nameEn: 'Oedipus Complex',
    description: '幼儿对异性父母的欲望和对同性父母的竞争。',
    definition: '俄狄浦斯情结是指幼儿对异性父母的潜意识欲望和对同性父母的竞争或敌意。这是心理发展的关键阶段，其解决方式影响个体的性别认同和人格发展。',
    example: '一个3-5岁的男孩可能表现出对母亲的特殊依恋，对父亲的竞争意识，这是正常的发展阶段。',
    category: 'phenomena',
    level: 2,
    color: '#F472B6',
  },
  {
    id: 'defense_mechanisms',
    name: '防御机制',
    nameEn: 'Defense Mechanisms',
    description: '自我用来应对焦虑和冲突的无意识策略。',
    definition: '防御机制是自我为了保护个体免受焦虑、冲突和痛苦而采用的无意识心理策略。这些机制扭曲、否认或隐藏现实，以维持心理平衡。',
    example: '一个人使用幽默来应对严肃的冲突情况，这是一种防御机制，帮助其减轻焦虑。',
    category: 'phenomena',
    level: 2,
    color: '#F472B6',
  },
  {
    id: 'resistance',
    name: '抵抗',
    nameEn: 'Resistance',
    description: '分析者无意识地抵抗分析过程，保护无意识内容。',
    definition: '抵抗是指分析者在治疗过程中无意识地抵抗，避免面对令人不快的无意识内容。表现为遗忘、沉默、迟到或改变话题等。',
    example: '患者在接近某个创伤话题时突然改变话题，或声称"想不起来"，这是抵抗的表现。',
    category: 'phenomena',
    level: 2,
    color: '#F472B6',
  },

  // 第三层：具体概念
  {
    id: 'libido',
    name: '力比多',
    nameEn: 'Libido',
    description: '心理能量或性欲驱力，驱动人类行为。',
    definition: '力比多是弗洛伊德理论中的心理能量或性欲驱力。它不仅指性欲，还指所有形式的心理能量和生命力，驱动个体的行为、思想和创造活动。',
    example: '艺术家的创作热情、运动员的竞争欲望，都可以被理解为力比多的升华表现。',
    category: 'phenomena',
    level: 3,
    color: '#FCA5A5',
  },
  {
    id: 'infantile_sexuality',
    name: '幼儿性欲',
    nameEn: 'Infantile Sexuality',
    description: '弗洛伊德认为儿童具有性欲，经历不同的发展阶段。',
    definition: '幼儿性欲理论认为儿童从出生起就具有性欲（广义的），并经历口腔期、肛门期、性器期等心理性发展阶段。这些阶段的经历影响成人的人格和性心理。',
    example: '婴儿通过吸吮获得快感（口腔期），幼儿通过排便控制获得满足感（肛门期），这些都是幼儿性欲的表现。',
    category: 'phenomena',
    level: 3,
    color: '#FCA5A5',
  },
  {
    id: 'pleasure_principle',
    name: '享乐原则',
    nameEn: 'Pleasure Principle',
    description: '本我遵循的原则，追求快乐和避免痛苦。',
    definition: '享乐原则是本我的基本运作原则，指个体自动地追求快乐、满足和舒适，同时避免痛苦、不适和紧张。',
    example: '一个饥饿的人会立即寻找食物来消除饥饿的不适，这就是享乐原则的直接体现。',
    category: 'phenomena',
    level: 3,
    color: '#FCA5A5',
  },
  {
    id: 'reality_principle',
    name: '现实原则',
    nameEn: 'Reality Principle',
    description: '自我遵循的原则，考虑现实的限制和后果。',
    definition: '现实原则是自我的运作原则，指个体在追求满足时考虑现实的限制、社会规范和长期后果，采用理性和延迟满足的方式。',
    example: '一个学生想要玩游戏（享乐原则），但意识到必须先完成作业（现实原则），所以延迟了玩游戏的时间。',
    category: 'phenomena',
    level: 3,
    color: '#FCA5A5',
  },
  {
    id: 'moral_principle',
    name: '道德原则',
    nameEn: 'Moral Principle',
    description: '超我遵循的原则，基于道德和社会规范。',
    definition: '道德原则是超我的运作原则，指个体根据内化的道德标准、社会规范和理想自我来指导行为，追求道德完美和社会认可。',
    example: '一个人拒绝做不诚实的事情，即使这样做能获得利益，因为道德原则驱使其保持诚实。',
    category: 'phenomena',
    level: 3,
    color: '#FCA5A5',
  },
  {
    id: 'condensation',
    name: '凝缩',
    nameEn: 'Condensation',
    description: '梦的工作机制，多个观念融合为一个梦的元素。',
    definition: '凝缩是梦的工作机制之一，指多个观念、人物或情感在梦中融合为一个单一的梦的元素。这使得梦的内容比现实生活更加浓缩和象征化。',
    example: '梦中出现的一个人物可能同时代表了梦者的父亲、老师和心理医生，这些人物的特征被凝缩在一个梦的人物中。',
    category: 'phenomena',
    level: 3,
    color: '#FCA5A5',
  },
  {
    id: 'displacement',
    name: '移置',
    nameEn: 'Displacement',
    description: '梦的工作机制，情感从一个对象转移到另一个。',
    definition: '移置是梦的工作机制之一，指梦中的情感、冲动或意义从其真实对象转移到另一个对象。这使得梦的真实意义被隐藏。',
    example: '一个人对上司感到愤怒，但在梦中，这种愤怒被转移到了一个陌生人身上。',
    category: 'phenomena',
    level: 3,
    color: '#FCA5A5',
  },
  {
    id: 'screen_memory',
    name: '屏记忆',
    nameEn: 'Screen Memory',
    description: '既阻挡又扭曲呈现记忆的无意识防御机制。',
    definition: '屏记忆是一种防御机制，指个体记住的某个看似平凡的事件，实际上是对另一个令人不快或创伤性事件的替代或扭曲。它既隐藏了真实记忆，又允许某些相关内容进入意识。',
    example: '一个人清晰地记得童年时一个看似无关紧要的事件，但这个记忆实际上是对某个创伤经历的屏障。',
    category: 'phenomena',
    level: 3,
    color: '#FCA5A5',
  },

  // 理论家
  {
    id: 'freud',
    name: '西格蒙德·弗洛伊德',
    nameEn: 'Sigmund Freud',
    description: '精神分析的创始人，奠基人。',
    definition: '弗洛伊德（1856-1939）是奥地利神经医生和精神分析学的创始人。他开创了精神分析理论和治疗方法，提出了无意识、本我-自我-超我、防御机制等核心概念，深刻影响了现代心理学、文化和社会思想。',
    example: '弗洛伊德通过治疗患有歇斯底里症的患者，发现了无意识的存在和压抑的作用，从而开创了精神分析学派。',
    category: 'theorist',
    level: 2,
    color: '#FBBF24',
  },
  {
    id: 'jung',
    name: '卡尔·荣格',
    nameEn: 'Carl Jung',
    description: '弗洛伊德的弟子，发展了分析心理学。',
    definition: '荣格（1875-1961）是瑞士精神病医生，最初是弗洛伊德的学生和同事。他后来发展了分析心理学，引入了集体无意识、原型、心理类型等概念，强调个体化和精神成长。',
    example: '荣格提出的"影子"原型概念，指个体无意识中被压抑的、不被接受的部分，这对现代心理治疗产生了重要影响。',
    category: 'theorist',
    level: 2,
    color: '#FBBF24',
  },
  {
    id: 'lacan',
    name: '雅各·拉康',
    nameEn: 'Jacques Lacan',
    description: '后继理论家，重新解释精神分析理论，强调语言的作用。',
    definition: '拉康（1901-1981）是法国精神分析家，对弗洛伊德理论进行了激进的重新解释，强调语言和符号在心理形成中的作用，提出了象征界、想象界、实在界等核心概念。',
    example: '拉康的镜像阶段理论解释了婴儿如何通过镜子中的形象建立自我认同，这个过程涉及想象界和象征界的相互作用。',
    category: 'theorist',
    level: 2,
    color: '#FBBF24',
  },
  {
    id: 'kohut',
    name: '海因茨·科胡特',
    nameEn: 'Heinz Kohut',
    description: '自体心理学的创始人，强调同理心和自体的重要性。',
    definition: '科胡特（1913-1981）是奥地利裔美国精神分析家，创立了自体心理学。他强调同理心在治疗中的中心作用，提出了自体客体的概念，认为个体需要通过与他人的关系来维持和发展自体。',
    example: '科胡特认为，母亲通过镜映婴儿的需求和感受，帮助婴儿建立健康的自体。缺乏这种镜映会导致自体缺陷。',
    category: 'theorist',
    level: 2,
    color: '#FBBF24',
  },
  {
    id: 'klein',
    name: '梅兰妮·克莱因',
    nameEn: 'Melanie Klein',
    description: '客体关系理论的先驱，强调内在客体和投射认同。',
    definition: '克莱因（1882-1960）是英国精神分析家，是客体关系理论的先驱。她强调婴幼儿期的心理发展，提出了分裂、投射认同等机制，认为内在客体的表征对人格发展至关重要。',
    example: '克莱因观察到婴儿将母亲分裂为"好乳房"和"坏乳房"，这种分裂是心理发展的正常阶段。',
    category: 'theorist',
    level: 2,
    color: '#FBBF24',
  },
  {
    id: 'winnicott',
    name: '唐纳德·温尼科特',
    nameEn: 'Donald Winnicott',
    description: '客体关系理论家，强调母婴关系和过渡对象。',
    definition: '温尼科特（1896-1971）是英国儿科医生和精神分析家，强调母婴关系的重要性。他提出了"足够好的母亲"、过渡对象和过渡空间等概念，对儿童心理发展和创造性的理解产生了深远影响。',
    example: '温尼科特的"过渡对象"概念解释了为什么幼儿会依恋毛绒玩具或毯子——这些对象帮助儿童从完全依赖母亲过渡到独立。',
    category: 'theorist',
    level: 2,
    color: '#FBBF24',
  },

  // 拉康理论
  {
    id: 'symbolic_order',
    name: '象征界',
    nameEn: 'Symbolic Order',
    description: '拉康三界之一。由语言、文化和社会规则组成。',
    definition: '象征界是拉康三界中的一个，由语言、文化、社会规则和法律组成。它是意义的领域，个体通过进入象征界获得语言和社会身份，但也因此受到符号秩序的限制。',
    example: '当一个婴儿被命名时，它进入了象征界，获得了社会身份和语言能力，但也受到了社会规范的约束。',
    category: 'lacan',
    level: 2,
    color: '#EC4899',
  },
  {
    id: 'imaginary_order',
    name: '想象界',
    nameEn: 'Imaginary Order',
    description: '拉康三界之一。自我与他人的镜像关系。',
    definition: '想象界是拉康三界中的一个，由自我与他人的镜像关系组成。在这个领域中，个体通过识别和镜像来形成自我认同，但这种认同是虚幻和分裂的。',
    example: '婴儿在镜子中看到自己的形象，产生了自我的幻觉，这是想象界的典型表现。',
    category: 'lacan',
    level: 2,
    color: '#EC4899',
  },
  {
    id: 'real_order',
    name: '实在界',
    nameEn: 'Real Order',
    description: '拉康三界之一。超越象征和想象的绝对他者。',
    definition: '实在界是拉康三界中最难理解的一个，指超越象征和想象的绝对他者，无法被语言或想象完全表达。它是创伤、死亡和绝对差异的领域。',
    example: '死亡是实在界的表现，它超越了我们的想象和语言表达能力，是绝对的他者。',
    category: 'lacan',
    level: 2,
    color: '#EC4899',
  },
  {
    id: 'mirror_stage',
    name: '镜像阶段',
    nameEn: 'Mirror Stage',
    description: '拉康理论中，婴儿通过镜像建立自我认同的阶段。',
    definition: '镜像阶段是拉康理论中的关键概念，指6-18个月的婴儿通过在镜子中看到自己的形象，产生了自我认同的幻觉。这个阶段标志着想象界的开始，但这种自我认同是虚幻和分裂的。',
    example: '当婴儿第一次在镜子中看到自己的完整形象时，产生了快乐和满足感，这标志着自我的诞生。',
    category: 'lacan',
    level: 3,
    color: '#F97316',
  },
  {
    id: 'lack',
    name: '缺失',
    nameEn: 'Lack',
    description: '拉康的核心概念，主体永远无法完全满足的根本缺失。',
    definition: '缺失是拉康理论的核心，指主体因进入象征界而产生的根本缺失。这种缺失是无法消除的，驱动着欲望的永恒循环，个体永远无法回到原始的完整状态。',
    example: '一个人追求完美的爱情或成功，但即使获得了这些，仍然感到某种无法名状的缺失和空虚，这就是拉康所说的根本缺失。',
    category: 'lacan',
    level: 3,
    color: '#F97316',
  },
  {
    id: 'desire',
    name: '欲望',
    nameEn: 'Desire',
    description: '拉康强调欲望不同于需求，是由语言和象征界产生的。',
    definition: '在拉康理论中，欲望不同于需求。需求是生物学的，而欲望是由语言和象征界产生的。欲望总是指向他者，总是被延迟和转移，永远无法得到完全满足。',
    example: '一个人可能需要食物来满足饥饿，但欲望一个特定的美食，这种欲望是由文化和语言形成的。',
    category: 'lacan',
    level: 3,
    color: '#F97316',
  },
  {
    id: 'jouissance',
    name: '享乐',
    nameEn: 'Jouissance',
    description: '拉康的关键概念，超越快乐原则的极端享受体验。',
    definition: '享乐是拉康理论中的关键概念，指超越快乐原则的极端享受体验。它既是快乐的，又是痛苦的，是一种与死亡本能相关的强烈而危险的满足。',
    example: '成瘾行为可以被理解为对享乐的追求，个体重复进行某种行为尽管知道这会带来痛苦，因为这种行为提供了超越普通快乐的极端体验。',
    category: 'lacan',
    level: 3,
    color: '#F97316',
  },

  // 自体心理学
  {
    id: 'self',
    name: '自体',
    nameEn: 'Self',
    description: '自体心理学的中心概念，人格的核心和统一性。',
    definition: '在自体心理学中，自体是人格的核心和统一性的源头。它不同于弗洛伊德的自我，而是指个体的核心身份、价值观和生命目标的整体感。健康的自体需要通过与自体客体的关系来维持和发展。',
    example: '一个人的自体包括其独特的才能、价值观和人生目标。当这个自体得到他人的认可和支持时，个体会感到完整和有活力。',
    category: 'self_psychology',
    level: 2,
    color: '#06B6D4',
  },
  {
    id: 'selfobject',
    name: '自体客体',
    nameEn: 'Selfobject',
    description: '他人作为自体的延伸，提供镜映、理想化和孪生体验。',
    definition: '自体客体是自体心理学的核心概念，指他人作为自体的心理延伸而被体验。自体客体通过镜映、理想化和孪生体验来支持和维持个体的自体。',
    example: '母亲作为婴儿的自体客体，通过镜映婴儿的需求和感受，帮助婴儿建立自体。',
    category: 'self_psychology',
    level: 2,
    color: '#06B6D4',
  },
  {
    id: 'mirroring',
    name: '镜映',
    nameEn: 'Mirroring',
    description: '自体客体通过反映和确认来支持自体的发展。',
    definition: '镜映是自体客体功能之一，指他人通过反映和确认个体的感受、需求和成就来支持个体的自体发展。这种镜映帮助个体建立自我价值感和自信。',
    example: '当父母为孩子的成就感到骄傲并表达出来时，孩子获得了镜映，这强化了孩子的自体和自信。',
    category: 'self_psychology',
    level: 3,
    color: '#14B8A6',
  },
  {
    id: 'idealization',
    name: '理想化',
    nameEn: 'Idealization',
    description: '个体将完美的品质投射到自体客体身上。',
    definition: '理想化是自体客体功能之一，指个体将完美、力量和智慧的品质投射到自体客体（如父母或导师）身上。这种理想化帮助个体内化这些品质，逐渐发展出自己的理想和目标。',
    example: '一个孩子将父亲理想化为完美和强大的人物，通过这种理想化，孩子逐渐内化了父亲的价值观和目标。',
    category: 'self_psychology',
    level: 3,
    color: '#14B8A6',
  },
  {
    id: 'twinship',
    name: '孪生体验',
    nameEn: 'Twinship',
    description: '与自体客体的相似性和共同性体验。',
    definition: '孪生体验是自体客体功能之一，指个体与自体客体之间的相似性和共同性体验。这种体验帮助个体感到被理解和接纳，增强了自体的完整性和价值感。',
    example: '当一个人找到志同道合的朋友，能够分享相同的兴趣和价值观时，这就是孪生体验，它增强了个体的自体感。',
    category: 'self_psychology',
    level: 3,
    color: '#14B8A6',
  },
  {
    id: 'empathy',
    name: '同理心',
    nameEn: 'Empathy',
    description: '自体心理学强调的治疗关键，进入他人的内在世界。',
    definition: '在自体心理学中，同理心是治疗的核心。它指分析师进入分析者的内在世界，理解其主观体验和感受。这种深层的同理理解本身就具有治疗效果。',
    example: '分析师不仅听患者的话，还试图理解患者的内在世界，感受其痛苦和渴望，这种同理心帮助患者修复自体缺陷。',
    category: 'self_psychology',
    level: 3,
    color: '#14B8A6',
  },

  // 客体关系理论
  {
    id: 'object_relations',
    name: '客体关系',
    nameEn: 'Object Relations',
    description: '强调内在客体表征和人际关系的理论。',
    definition: '客体关系理论强调个体内心中他人的心理表征（内在客体）对人格和行为的影响。这个理论认为，人与人之间的关系，特别是早期的母婴关系，塑造了个体的内在世界和人际关系模式。',
    example: '一个在童年缺乏安全依恋的人，可能在成年后的亲密关系中表现出不信任和回避，因为他内在的客体表征是不安全的。',
    category: 'object_relations',
    level: 2,
    color: '#8B5CF6',
  },
  {
    id: 'internal_object',
    name: '内在客体',
    nameEn: 'Internal Object',
    description: '个体内心中他人的心理表征，受投射和内摄影响。',
    definition: '内在客体是个体内心中他人的心理表征，是通过内摄（吸收他人的特质）和投射（将自己的特质投射到他人）形成的。这些内在客体对个体的思维、感受和行为产生深远影响。',
    example: '一个人可能在心中保持着对已故父亲的内在表征，这个内在客体继续影响着这个人的决定和行为。',
    category: 'object_relations',
    level: 3,
    color: '#A855F7',
  },
  {
    id: 'projective_identification',
    name: '投射认同',
    nameEn: 'Projective Identification',
    description: '克莱因理论，将内在冲突投射到他人身上并认同。',
    definition: '投射认同是克莱因提出的复杂心理过程，个体不仅将内在冲突或特质投射到他人身上，还试图通过影响他人来控制这些投射内容。这是一种原始的沟通和防御形式。',
    example: '一个充满愤怒的人可能会激怒他人，然后通过他人的愤怒来体验和处理自己的愤怒。',
    category: 'object_relations',
    level: 3,
    color: '#A855F7',
  },
  {
    id: 'introjection',
    name: '内摄',
    nameEn: 'Introjection',
    description: '将外部客体的特质吸收到自我中。',
    definition: '内摄是指个体将外部客体（通常是重要他人）的特质、价值观和行为模式吸收到自我中。这是人格发展的重要机制，但如果内摄的对象是有害的，也可能导致心理问题。',
    example: '一个孩子通过内摄父母的道德标准和价值观，逐渐形成了自己的超我。',
    category: 'object_relations',
    level: 3,
    color: '#A855F7',
  },
  {
    id: 'good_bad_object',
    name: '好坏客体',
    nameEn: 'Good and Bad Object',
    description: '克莱因的分裂理论，婴儿将客体分为全好或全坏。',
    definition: '好坏客体是克莱因的分裂理论，指婴儿在早期发展阶段将客体（特别是母亲）分裂为全好或全坏。当母亲满足需求时是"好乳房"，当母亲不在或拒绝时是"坏乳房"。这种分裂是正常的发展阶段。',
    example: '一个婴儿可能在饥饿时对母亲充满敌意（坏客体），但在被喂食后对母亲充满爱（好客体），这种分裂是正常的。',
    category: 'object_relations',
    level: 3,
    color: '#A855F7',
  },
  {
    id: 'transitional_object',
    name: '过渡客体',
    nameEn: 'Transitional Object',
    description: '温尼科特理论，儿童用来过渡的物体（如毛绒玩具）。',
    definition: '过渡客体是温尼科特提出的概念，指儿童用来从完全依赖母亲过渡到独立的物体，如毛绒玩具或毯子。这个物体既代表母亲，又是独立的，帮助儿童发展创造性和独立性。',
    example: '一个幼儿依恋的泰迪熊是过渡客体，它帮助孩子在母亲不在时感到安慰，逐渐学会独立。',
    category: 'object_relations',
    level: 3,
    color: '#A855F7',
  },
  {
    id: 'holding_environment',
    name: '容纳环境',
    nameEn: 'Holding Environment',
    description: '温尼科特概念，母亲提供的安全、支持的环境。',
    definition: '容纳环境是温尼科特提出的概念，指母亲为婴儿提供的安全、支持和照顾的环境。在这个环境中，婴儿的需求被理解和满足，婴儿发展出对世界的基本信任和安全感。',
    example: '一个母亲通过温柔的触摸、回应性的照顾和情感支持，为婴儿创造了一个容纳环境，帮助婴儿发展出安全感。',
    category: 'object_relations',
    level: 3,
    color: '#A855F7',
  },
];

export const conceptLinks: ConceptLink[] = [
  // 无意识与人格结构
  { source: 'unconscious', target: 'id', type: 'contains', strength: 1 },
  { source: 'unconscious', target: 'ego', type: 'influences', strength: 0.8 },
  { source: 'unconscious', target: 'superego', type: 'influences', strength: 0.7 },

  // 人格结构之间
  { source: 'id', target: 'ego', type: 'relates', strength: 0.9 },
  { source: 'ego', target: 'superego', type: 'relates', strength: 0.9 },
  { source: 'id', target: 'superego', type: 'relates', strength: 0.7 },

  // 无意识与防御机制
  { source: 'unconscious', target: 'repression', type: 'manifests', strength: 1 },
  { source: 'unconscious', target: 'denial', type: 'manifests', strength: 0.9 },
  { source: 'unconscious', target: 'projection', type: 'manifests', strength: 0.8 },
  { source: 'unconscious', target: 'sublimation', type: 'manifests', strength: 0.8 },

  // 自我与防御机制
  { source: 'ego', target: 'repression', type: 'relates', strength: 0.9 },
  { source: 'ego', target: 'defense_mechanisms', type: 'contains', strength: 1 },

  // 无意识与治疗方法
  { source: 'unconscious', target: 'free_association', type: 'treats', strength: 1 },
  { source: 'unconscious', target: 'dream_analysis', type: 'treats', strength: 1 },
  { source: 'unconscious', target: 'transference', type: 'treats', strength: 0.9 },

  // 治疗方法之间
  { source: 'free_association', target: 'interpretation', type: 'relates', strength: 0.9 },
  { source: 'dream_analysis', target: 'interpretation', type: 'relates', strength: 0.9 },
  { source: 'transference', target: 'interpretation', type: 'relates', strength: 0.8 },

  // 心理现象
  { source: 'unconscious', target: 'psychic_determinism', type: 'manifests', strength: 1 },
  { source: 'unconscious', target: 'oedipus_complex', type: 'manifests', strength: 0.9 },
  { source: 'unconscious', target: 'resistance', type: 'manifests', strength: 0.9 },

  // 具体概念与抽象概念
  { source: 'id', target: 'libido', type: 'relates', strength: 0.9 },
  { source: 'id', target: 'pleasure_principle', type: 'relates', strength: 1 },
  { source: 'ego', target: 'reality_principle', type: 'relates', strength: 1 },
  { source: 'superego', target: 'moral_principle', type: 'relates', strength: 1 },

  // 梦的工作机制
  { source: 'dream_analysis', target: 'condensation', type: 'relates', strength: 0.9 },
  { source: 'dream_analysis', target: 'displacement', type: 'relates', strength: 0.9 },

  // 屏记忆
  { source: 'unconscious', target: 'screen_memory', type: 'manifests', strength: 0.8 },

  // 理论家与概念
  { source: 'freud', target: 'unconscious', type: 'relates', strength: 1 },
  { source: 'freud', target: 'id', type: 'relates', strength: 1 },
  { source: 'freud', target: 'oedipus_complex', type: 'relates', strength: 0.9 },
  { source: 'jung', target: 'unconscious', type: 'relates', strength: 0.8 },
  { source: 'lacan', target: 'unconscious', type: 'relates', strength: 0.8 },
  { source: 'kohut', target: 'self', type: 'relates', strength: 1 },
  { source: 'klein', target: 'object_relations', type: 'relates', strength: 1 },
  { source: 'winnicott', target: 'object_relations', type: 'relates', strength: 1 },

  // 拉康理论与无意识
  { source: 'unconscious', target: 'symbolic_order', type: 'relates', strength: 0.9 },
  { source: 'unconscious', target: 'imaginary_order', type: 'relates', strength: 0.8 },
  { source: 'unconscious', target: 'real_order', type: 'relates', strength: 0.8 },
  { source: 'symbolic_order', target: 'desire', type: 'relates', strength: 0.9 },
  { source: 'imaginary_order', target: 'mirror_stage', type: 'relates', strength: 1 },
  { source: 'real_order', target: 'jouissance', type: 'relates', strength: 0.9 },
  { source: 'symbolic_order', target: 'lack', type: 'relates', strength: 0.9 },

  // 自体心理学与无意识
  { source: 'unconscious', target: 'self', type: 'relates', strength: 0.8 },
  { source: 'self', target: 'selfobject', type: 'contains', strength: 1 },
  { source: 'selfobject', target: 'mirroring', type: 'manifests', strength: 0.9 },
  { source: 'selfobject', target: 'idealization', type: 'manifests', strength: 0.9 },
  { source: 'selfobject', target: 'twinship', type: 'manifests', strength: 0.8 },
  { source: 'empathy', target: 'mirroring', type: 'relates', strength: 0.9 },

  // 客体关系与无意识
  { source: 'unconscious', target: 'object_relations', type: 'relates', strength: 0.9 },
  { source: 'object_relations', target: 'internal_object', type: 'contains', strength: 1 },
  { source: 'internal_object', target: 'projective_identification', type: 'manifests', strength: 0.9 },
  { source: 'internal_object', target: 'introjection', type: 'manifests', strength: 0.9 },
  { source: 'internal_object', target: 'good_bad_object', type: 'manifests', strength: 0.8 },
  { source: 'object_relations', target: 'transitional_object', type: 'relates', strength: 0.8 },
  { source: 'object_relations', target: 'holding_environment', type: 'relates', strength: 0.8 },

  // 防御机制与客体关系
  { source: 'projection', target: 'projective_identification', type: 'relates', strength: 0.8 },
  { source: 'defense_mechanisms', target: 'introjection', type: 'relates', strength: 0.7 },

  // 转移与自体心理学
  { source: 'transference', target: 'selfobject', type: 'relates', strength: 0.8 },
  { source: 'transference', target: 'empathy', type: 'relates', strength: 0.7 },

  // 拉康理论之间的关系
  { source: 'mirror_stage', target: 'imaginary_order', type: 'relates', strength: 0.9 },
  { source: 'desire', target: 'lack', type: 'relates', strength: 0.9 },
  { source: 'jouissance', target: 'real_order', type: 'relates', strength: 0.9 },
];

export const categoryColors = {
  core: '#D97706',
  personality: '#A78BFA',
  defense: '#A78BFA',
  therapy: '#34D399',
  phenomena: '#F472B6',
  theorist: '#FBBF24',
  lacan: '#EC4899',
  self_psychology: '#06B6D4',
  object_relations: '#8B5CF6',
};

export const categoryLabels = {
  core: '核心概念',
  personality: '人格结构',
  defense: '防御机制',
  therapy: '治疗方法',
  phenomena: '心理现象',
  theorist: '理论家',
  lacan: '拉康理论',
  self_psychology: '自体心理学',
  object_relations: '客体关系',
};
